const APP_VERSION="0.2.0";
const DB_NAME="starcatcher-sm"; const DB_VERSION=1; const SHOW_KEY="show"; const CHECK_KEY="checks"; const META_KEY="meta";
let db, showData, checks={}, currentView="home", runFilter="ALL", runSearch="", editTab="presets", deferredPrompt=null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function now(){return new Date().toISOString();}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains("kv"))d.createObjectStore("kv")};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function getKV(k){return new Promise((res,rej)=>{const t=db.transaction("kv","readonly"),r=t.objectStore("kv").get(k);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function setKV(k,v){return new Promise((res,rej)=>{const t=db.transaction("kv","readwrite"),r=t.objectStore("kv").put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}
async function init(){db=await openDB();const starter=await (await fetch("data/seed-show.json",{cache:"no-store"})).json();showData=await getKV(SHOW_KEY);checks=await getKV(CHECK_KEY)||{};if(!showData){showData=starter;await setKV(SHOW_KEY,showData);}else if(showData.appVersion!==APP_VERSION){showData=migrateToStarter(showData,starter);await setKV(SHOW_KEY,showData);}$("#productionTitle").textContent=showData.production?.title||"Stage Manager";bindShell();route("home");registerSW();}
function overlayById(seedRows,localRows){const local=new Map((localRows||[]).map(x=>[x.id,x]));return (seedRows||[]).map(x=>local.has(x.id)?{...x,...local.get(x.id),updatedAt:local.get(x.id).updatedAt||x.updatedAt}:x).concat((localRows||[]).filter(x=>String(x.id||"").includes("-custom-")&&!seedRows.some(s=>s.id===x.id)));}
function migrateToStarter(local,starter){return {...starter,props:overlayById(starter.props,local.props),movements:overlayById(starter.movements,local.movements),people:overlayById(starter.people,local.people),presets:[...starter.presets,...(local.presets||[]).filter(x=>String(x.id||"").startsWith("preset-custom-"))],images:starter.images,changeover:starter.changeover,appVersion:APP_VERSION};}
function bindShell(){ $$(".navbtn").forEach(b=>b.addEventListener("click",()=>route(b.dataset.view)));$("#closePhoto").addEventListener("click",()=>$("#photoDialog").close());$("#photoDialog").addEventListener("click",e=>{if(e.target===$("#photoDialog"))$("#photoDialog").close()});window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});$("#installBtn").addEventListener("click",async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").hidden=true});$("#importFile").addEventListener("change",handleImportFile);}
function route(v){currentView=v;$$(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="home")renderHome();else if(v==="act1")renderPreset("I");else if(v==="act2")renderPreset("II");else if(v==="run")renderRun();else if(v==="change")renderChange();else renderEdit();window.scrollTo({top:0,behavior:"instant"});}
function totalChecks(act){const a=showData.presets.filter(x=>x.act===act);return [a.filter(x=>checks[x.id]).length,a.length];}
function progressHTML(done,total){const p=total?Math.round(done/total*100):0;return `<div class="progressline"><div class="progress"><span style="width:${p}%"></span></div><small>${done}/${total} · ${p}%</small></div>`;}
function renderHome(){const [d1,t1]=totalChecks("I"),[d2,t2]=totalChecks("II");const reviews=showData.movements.filter(m=>m.review).length+showData.props.filter(p=>p.review).length;const last=localStorage.getItem("lastExport")||"Not yet";$("#view").innerHTML=`<div class="kpis"><div class="kpi"><b>${d1}/${t1}</b><span>Act I preset</span></div><div class="kpi"><b>${d2}/${t2}</b><span>Act II preset</span></div><div class="kpi"><b>${showData.movements.length}</b><span>Run entries</span></div><div class="kpi"><b>${reviews}</b><span>Review flags</span></div></div><div class="grid"><button class="homebtn" data-go="act1"><strong>Act I Preset</strong><small>Checklist + reference photos</small></button><button class="homebtn" data-go="run"><strong>Run Track</strong><small>Movement list from the props sheet</small></button><button class="homebtn" data-go="change"><strong>Intermission</strong><small>Act I → Act II changeover</small></button><button class="homebtn" data-go="act2"><strong>Act II Preset</strong><small>Checklist + reference photos</small></button><button class="homebtn" data-go="edit"><strong>Edit Show</strong><small>Presets, movements and props</small></button><button class="homebtn" id="backupHome"><strong>Backup / Share</strong><small>Last export: ${esc(last)}</small></button></div><div class="card" style="margin-top:14px"><div class="stateline"><b>Offline data</b><span>App v${APP_VERSION}</span></div><p class="filemeta">Show edits are stored on this device. Presets use the October 2026 production documents; movement tracking comes from the prop spreadsheet. Export after meaningful edits so another device can merge the update.</p></div>`;$$('[data-go]').forEach(b=>b.addEventListener('click',()=>route(b.dataset.go)));$("#backupHome").addEventListener("click",()=>{editTab="data";route("edit")});}
function photoStrip(act,ids=null){let arr=showData.images?.[act==="I"?"act1":"act2"]||[];if(ids&&ids.length){const wanted=new Set(ids);arr=arr.filter(x=>wanted.has(x.id));}return `<div class="photo-strip">${arr.map(x=>`<button type="button" class="photo-thumb" data-photo="${esc(x.src)}" data-caption="${esc(x.label)}"><img loading="lazy" src="${esc(x.src)}" alt="${esc(x.label)}"><span>${esc(x.label)}</span></button>`).join("")}</div>`;}
function sectionRefs(items){return [...new Set(items.flatMap(x=>x.imageRefs||[]))];}
function bindPhotos(){ $$("[data-photo]").forEach(b=>b.addEventListener("click",()=>{$("#photoFull").src=b.dataset.photo;$("#photoCaption").textContent=b.dataset.caption;$("#photoDialog").showModal()}));}
function renderPreset(act){const rows=showData.presets.filter(x=>x.act===act);const done=rows.filter(x=>checks[x.id]).length;const groups=Object.groupBy?Object.groupBy(rows,x=>x.area):rows.reduce((a,x)=>((a[x.area]??=[]).push(x),a),{});const src=act==="I"?"Act I written preset + backstage prop list":"Act II written changeover/preset + backstage additions";$("#view").innerHTML=`<h2>Act ${act} Preset</h2><div class="sourcebar">${esc(src)}</div>${progressHTML(done,rows.length)}<div class="toolbar"><button id="resetChecks" class="ghost small">Reset Act ${act}</button><button id="checkAll" class="ghost small">Check all</button></div><details class="card reference-all"><summary>All Act ${act} reference photos</summary>${photoStrip(act)}</details>${Object.entries(groups).map(([area,items])=>{const refs=sectionRefs(items);return `<section class="card section"><div class="section-head"><h3>${esc(area)}</h3><small>${items.filter(i=>checks[i.id]).length}/${items.length}</small></div>${refs.length?`<div class="section-photos">${photoStrip(act,refs)}</div>`:""}${items.map(i=>`<label class="checkrow ${checks[i.id]?"done":""}"><input type="checkbox" data-check="${i.id}" ${checks[i.id]?"checked":""}><div class="itemtext"><div>${esc(i.item)}</div>${i.notes?`<div class="sub">${esc(i.notes)}</div>`:""}</div>${i.critical?'<span class="pill critical">critical</span>':''}</label>`).join("")}</section>`}).join("")}`;bindPhotos();$$('[data-check]').forEach(c=>c.addEventListener('change',async()=>{checks[c.dataset.check]=c.checked;await setKV(CHECK_KEY,checks);renderPreset(act)}));$("#resetChecks").addEventListener("click",async()=>{if(!confirm(`Reset all Act ${act} checks?`))return;rows.forEach(x=>delete checks[x.id]);await setKV(CHECK_KEY,checks);renderPreset(act)});$("#checkAll").addEventListener("click",async()=>{rows.forEach(x=>checks[x.id]=true);await setKV(CHECK_KEY,checks);renderPreset(act)});}
function movementSort(a,b){const rank=x=>x==="I"?1:x==="II"?2:9;return rank(a.act)-rank(b.act)||(parseFloat(a.scene)||99)-(parseFloat(b.scene)||99)||(parseFloat(a.page)||999)-(parseFloat(b.page)||999)||a.order-b.order;}
function renderRun(){const people=[...new Set(showData.movements.flatMap(x=>(x.person||"").split(/,|\//).map(s=>s.trim()).filter(Boolean)))].sort();let rows=showData.movements.slice().sort(movementSort);if(runFilter!=="ALL")rows=rows.filter(x=>x.act===runFilter||x.person.toLowerCase().includes(runFilter.toLowerCase()));if(runSearch)rows=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(runSearch.toLowerCase()));$("#view").innerHTML=`<h2>Run Track</h2><input id="runSearch" class="searchbar" placeholder="Search prop, person, page, cue…" value="${esc(runSearch)}"><div class="filters"><button class="filter ${runFilter==='ALL'?'active':''}" data-filter="ALL">All</button><button class="filter ${runFilter==='I'?'active':''}" data-filter="I">Act I</button><button class="filter ${runFilter==='II'?'active':''}" data-filter="II">Act II</button>${people.slice(0,12).map(p=>`<button class="filter ${runFilter===p?'active':''}" data-filter="${esc(p)}">${esc(p)}</button>`).join('')}</div><div class="card">${rows.length?rows.map(m=>`<div class="move ${m.review?'review':''}"><div class="move-top"><div class="move-name">${esc(m.propName)}</div><div class="move-meta">${m.act?`Act ${esc(m.act)}`:''}${m.scene?` · Sc ${esc(m.scene)}`:''}${m.page?` · p${esc(m.page)}`:''}</div></div><div class="move-detail">${m.cue&&m.cue!=='Initial / preset movement'?`<div><b>Cue:</b> ${esc(m.cue)}</div>`:''}${m.person?`<div><b>Who:</b> ${esc(m.person)}</div>`:''}${m.from||m.to?`<div><b>Move:</b> ${esc(m.from||'—')} → ${esc(m.to||'—')}</div>`:''}${m.review?'<div class="pill warn" style="margin-top:6px">review</div>':''}</div></div>`).join(''):'<div class="empty">No matching movements.</div>'}</div>`;$("#runSearch").addEventListener("input",e=>{runSearch=e.target.value;renderRun()});$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{runFilter=b.dataset.filter;renderRun()}));}
function renderChange(){const rows=showData.changeover;const done=rows.filter(x=>checks[x.id]).length;const groups=rows.reduce((a,x)=>((a[x.area]??=[]).push(x),a),{});$("#view").innerHTML=`<h2>Intermission Changeover</h2><div class="notice">This is the Act II setup/change list. Verify against the Act II reference photos before calling places.</div>${progressHTML(done,rows.length)}<div class="toolbar"><button id="resetChange" class="ghost small">Reset changeover</button><button id="viewA2" class="ghost small">Act II photos</button></div>${Object.entries(groups).map(([area,items])=>`<section class="card"><div class="section-head"><h3>${esc(area)}</h3><small>${items.filter(i=>checks[i.id]).length}/${items.length}</small></div>${items.map(i=>`<label class="checkrow ${checks[i.id]?"done":""}"><input type="checkbox" data-change="${i.id}" ${checks[i.id]?"checked":""}><div class="itemtext">${esc(i.item)}</div></label>`).join('')}</section>`).join('')}`;$$('[data-change]').forEach(c=>c.addEventListener('change',async()=>{checks[c.dataset.change]=c.checked;await setKV(CHECK_KEY,checks);renderChange()}));$("#resetChange").addEventListener("click",async()=>{if(!confirm('Reset intermission checks?'))return;rows.forEach(x=>delete checks[x.id]);await setKV(CHECK_KEY,checks);renderChange()});$("#viewA2").addEventListener("click",()=>route('act2'));}
function renderEdit(){const tabs=[['presets','Presets'],['movements','Movements'],['props','Props'],['data','Backup / Import']];$("#view").innerHTML=`<h2>Edit Show</h2><div class="edit-tabs">${tabs.map(([k,l])=>`<button class="filter ${editTab===k?'active':''}" data-edit-tab="${k}">${l}</button>`).join('')}</div><div id="editBody"></div>`;$$('[data-edit-tab]').forEach(b=>b.addEventListener('click',()=>{editTab=b.dataset.editTab;renderEdit()}));if(editTab==='presets')renderEditPresets();else if(editTab==='movements')renderEditMovements();else if(editTab==='props')renderEditProps();else renderDataTools();}
function editBody(html){$("#editBody").innerHTML=html;}
function renderEditPresets(){const rows=showData.presets;editBody(`<div class="toolbar"><button id="addPreset" class="primary small">+ Add preset item</button></div><div class="card">${rows.map(x=>`<div class="listrow"><div><b>Act ${esc(x.act)} · ${esc(x.area)}</b><div>${esc(x.item)}</div><div class="meta">${x.critical?'Critical · ':''}${x.notes?esc(x.notes):''}</div></div><div class="listrow-actions"><button class="ghost small" data-edit-preset="${x.id}">Edit</button><button class="danger small" data-del-preset="${x.id}">×</button></div></div>`).join('')}</div>`);$("#addPreset").addEventListener('click',()=>openPresetForm());$$('[data-edit-preset]').forEach(b=>b.addEventListener('click',()=>openPresetForm(showData.presets.find(x=>x.id===b.dataset.editPreset))));$$('[data-del-preset]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Delete this preset item?'))return;showData.presets=showData.presets.filter(x=>x.id!==b.dataset.delPreset);await saveShow();renderEdit()}));}
function openPresetForm(x={}){openForm('Preset item',[['act','Act','select',x.act||'I',['I','II']],['area','Area','text',x.area||''],['item','Item','text',x.item||''],['notes','Notes','textarea',x.notes||''],['critical','Critical','checkbox',!!x.critical]],async vals=>{if(x.id)Object.assign(x,vals,{updatedAt:now()});else showData.presets.push({id:'preset-custom-'+Date.now(),propId:'',imageRefs:[],...vals,updatedAt:now()});await saveShow();renderEdit()});}
function renderEditMovements(){const rows=showData.movements.slice().sort(movementSort);editBody(`<div class="toolbar"><button id="addMove" class="primary small">+ Add movement</button></div><div class="card">${rows.map(x=>`<div class="listrow"><div><b>${esc(x.propName)}</b><div class="meta">Act ${esc(x.act||'—')} · Sc ${esc(x.scene||'—')} · p${esc(x.page||'—')} · ${esc(x.person||'unassigned')}</div><div>${esc(x.cue||'')}</div></div><div class="listrow-actions"><button class="ghost small" data-edit-move="${x.id}">Edit</button><button class="danger small" data-del-move="${x.id}">×</button></div></div>`).join('')}</div>`);$("#addMove").addEventListener('click',()=>openMoveForm());$$('[data-edit-move]').forEach(b=>b.addEventListener('click',()=>openMoveForm(showData.movements.find(x=>x.id===b.dataset.editMove))));$$('[data-del-move]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Delete this movement?'))return;showData.movements=showData.movements.filter(x=>x.id!==b.dataset.delMove);await saveShow();renderEdit()}));}
function openMoveForm(x={}){const names=showData.props.map(p=>p.name).sort();openForm('Movement',[['propName','Prop','select',x.propName||names[0],names],['act','Act','select',x.act||'I',['I','II','']],['scene','Scene','text',x.scene||''],['page','Page','text',x.page||''],['person','Who','text',x.person||''],['from','From','text',x.from||''],['to','To','text',x.to||''],['cue','Cue / instruction','textarea',x.cue||''],['review','Needs review','checkbox',!!x.review]],async vals=>{const p=showData.props.find(p=>p.name===vals.propName);const data={...vals,propId:p?.id||'',updatedAt:now()};if(x.id)Object.assign(x,data);else showData.movements.push({id:'move-custom-'+Date.now(),order:99999,...data});await saveShow();renderEdit()});}
function renderEditProps(){editBody(`<div class="toolbar"><button id="addProp" class="primary small">+ Add prop</button></div><div class="card">${showData.props.map(x=>`<div class="listrow"><div><b>${esc(x.name)}</b><div class="meta">${x.review?'Needs review · ':''}${esc(x.notes||'')}</div></div><div class="listrow-actions"><button class="ghost small" data-edit-prop="${x.id}">Edit</button><button class="danger small" data-del-prop="${x.id}">×</button></div></div>`).join('')}</div>`);$("#addProp").addEventListener('click',()=>openPropForm());$$('[data-edit-prop]').forEach(b=>b.addEventListener('click',()=>openPropForm(showData.props.find(x=>x.id===b.dataset.editProp))));$$('[data-del-prop]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Delete this prop? Existing movement references will remain.'))return;showData.props=showData.props.filter(x=>x.id!==b.dataset.delProp);await saveShow();renderEdit()}));}
function openPropForm(x={}){openForm('Prop',[['name','Name','text',x.name||''],['notes','Notes','textarea',x.notes||''],['ready','Ready / acquired','checkbox',!!x.ready],['review','Needs review','checkbox',!!x.review]],async vals=>{if(x.id)Object.assign(x,vals,{updatedAt:now()});else showData.props.push({id:'prop-custom-'+Date.now(),sourcePage:'',sourceRow:'',...vals,updatedAt:now()});await saveShow();renderEdit()});}
function openForm(title,fields,onSave){$("#formFields").innerHTML=`<h2>${esc(title)}</h2>`+fields.map(([k,l,t,v,opts])=>{if(t==='select')return `<div class="formgroup"><label>${esc(l)}</label><select name="${k}">${opts.map(o=>`<option ${String(o)===String(v)?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`;if(t==='textarea')return `<div class="formgroup"><label>${esc(l)}</label><textarea name="${k}">${esc(v)}</textarea></div>`;if(t==='checkbox')return `<div class="formgroup"><label><input type="checkbox" name="${k}" ${v?'checked':''}> ${esc(l)}</label></div>`;return `<div class="formgroup"><label>${esc(l)}</label><input name="${k}" value="${esc(v)}"></div>`}).join('');const dlg=$("#formDialog");dlg.showModal();$("#editForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),vals={};fields.forEach(([k,l,t])=>vals[k]=t==='checkbox'?e.target.elements[k].checked:fd.get(k));await onSave(vals);dlg.close();};}
async function saveShow(){showData.production.updatedAt=now();await setKV(SHOW_KEY,showData);}
function renderDataTools(){const last=localStorage.getItem('lastExport')||'Not yet';editBody(`<div class="card"><h3>Backup / Share</h3><p class="filemeta">Exports contain the editable show data. Reference photos stay bundled with the app.</p><div class="toolbar"><button id="exportData" class="primary">Export data</button><button id="importMerge" class="ghost">Import + merge</button><button id="importReplace" class="ghost">Import + replace</button></div><div class="stateline"><b>Last export</b><span>${esc(last)}</span></div></div><div class="card"><h3>App / Image bundle</h3><p class="filemeta">App v${esc(showData.appVersion||APP_VERSION)} · Images ${esc(showData.imageBundleVersion||'—')}</p><p class="filemeta">To permanently replace preset photos, replace the matching image files in the app bundle and publish a new version.</p></div><div class="card"><h3>Recovery</h3><p class="filemeta">Reset the local editable data back to the bundled starter copy. This does not delete the PWA.</p><button id="resetSeed" class="danger">Reset to starter data</button></div>`);$("#exportData").addEventListener('click',exportData);$("#importMerge").addEventListener('click',()=>chooseImport('merge'));$("#importReplace").addEventListener('click',()=>chooseImport('replace'));$("#resetSeed").addEventListener('click',resetSeed);}
function exportData(){const data={...showData,exportedAt:now()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Starcatcher-show-data-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);const stamp=new Date().toLocaleString();localStorage.setItem('lastExport',stamp);renderDataTools();}
function chooseImport(mode){$("#importFile").dataset.mode=mode;$("#importFile").value='';$("#importFile").click();}
function validateIncoming(x){return x&&typeof x==='object'&&Array.isArray(x.props)&&Array.isArray(x.movements)&&Array.isArray(x.presets);}
async function handleImportFile(e){const f=e.target.files?.[0];if(!f)return;try{const incoming=JSON.parse(await f.text());if(!validateIncoming(incoming))throw new Error('Not a valid Starcatcher show data file.');const mode=e.target.dataset.mode||'merge';if(mode==='replace'){if(!confirm('Replace all local show data with this file?'))return;showData=incoming;}else{showData=mergeShow(showData,incoming);}await saveShow();alert(`Import complete (${mode}).`);renderDataTools();}catch(err){alert('Import failed: '+err.message);}}
function mergeById(local,incoming){const map=new Map(local.map(x=>[x.id,x]));for(const x of incoming){const cur=map.get(x.id);if(!cur){map.set(x.id,x);continue}const a=Date.parse(cur.updatedAt||0),b=Date.parse(x.updatedAt||0);if(!a||!b||b>=a)map.set(x.id,x);}return [...map.values()];}
function mergeShow(a,b){return {...a,production:{...a.production,...b.production},props:mergeById(a.props,b.props),movements:mergeById(a.movements,b.movements),presets:mergeById(a.presets,b.presets),changeover:mergeById(a.changeover||[],b.changeover||[]),people:mergeById(a.people||[],b.people||[]),images:a.images};}
async function resetSeed(){if(!confirm('Reset all editable show data to the starter copy?'))return;showData=await (await fetch('data/seed-show.json',{cache:'no-store'})).json();checks={};await setKV(SHOW_KEY,showData);await setKV(CHECK_KEY,checks);renderDataTools();}
async function registerSW(){if('serviceWorker' in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn('SW registration failed',e)}}}
init().catch(e=>{$("#view").innerHTML=`<div class="notice">App startup error: ${esc(e.message)}</div>`;console.error(e)});